### ISSUE TITLE
Crazy results

### ISSUE THREAD

**Issue by dillfrescott** [kaitz/fxcm#1]
This compressor is crazy good, was testing it on relatively small text files but the results are very very good also its very fast. Great work.

**Comment by kaitz** [comment]
Thanks. Well it has it's problems. It targets Wikipedia dump, so it has some contexts that are not suited for plain text and the input must be processed in a certain way.
Last time i targeted plain text it was v15.

**Comment by jreoka** [comment]
Ohhh gotcha!
